### ISSUE TITLE
下载安装ringging

### ISSUE THREAD

**Issue by kelify** [alibaba/derrick#1]
根据文档中的提示使用pip来安装相应的ringging包下载不了

**Comment by ringtail** [comment]
pip install 的Rigging是需要开发者自己来编写的，近期会开放一批Rigging出来，如果开发者期望使用什么框架，可以在issue中回复，我会先开放出几个可以安装的第三方Rigging

**Comment by ringtail** [comment]
默认情况下Derrick回内置MavenRigging NodejsRigging以及PythonRigging，可以先看看是否能够满足业务需求
