### ISSUE TITLE
REGISTRY_ENDPOINT and IMAGE_WITH_TAG could not setting separtely in Spring Cloud project.

### ISSUE THREAD

**Issue by highkay** [alibaba/derrick#24]
1.derrick init
2.hint me "? What's your image repo"
3.input the repo(I wonder it means the registry), so it would be registry.x.y
4.in the derrick_conf, I found the ""image_with_tag": "registry.x.y"":(
5.on the other hand, if I input the image_with_tag, for example, helloworld
6.the REGISTRY_ENDPOINT in Jenkinsfile would be "helloworld":(

So I wonder REGISTRY_ENDPOINT and IMAGE_WITH_TAG should be setting separtely to fix the bug.

**Comment by ringtail** [comment]
Yes, "What's your image repo" is a little confused, I will change it to "Please input your image name with tag like `registry.aliyuncs.com/ringtail/demo:latest`.  


""

**Comment by highkay** [comment]
Cool.

**Comment by ringtail** [comment]
@highkay you can run `pip install -i https://pypi.python.org/simple --upgrade python-derrick==0.0.19` to upgrade derrick
