### ISSUE TITLE
Incompatible with prompt_toolkit version 2.0

### ISSUE THREAD

**Issue by zsefvlol** [alibaba/derrick#29]
The package [whaaaaat](https://github.com/finklabs/whaaaaat) is incompatible with [prompt_toolkit](https://github.com/jonathanslenders/python-prompt-toolkit) version 2.0. So for new users or one who just upgraded prompt_toolkit would incounter error when using derrick.

```
Failed to load rigging or commands in disk,because of cannot import name Token
```

I already post the [issue](https://github.com/finklabs/whaaaaat/issues/23) to that whaaaaat.

Temporary fix:
```bash
pip uninstall prompt-toolkit
pip install -Iv prompt_toolkit==1.0.15
```

May consider other packages before whaaaaat fix that.

**Comment by ringtail** [comment]
ok, I will fix the package dependency.
