### ISSUE TITLE
安装不成功，是什么原因？

### ISSUE THREAD

**Issue by jearton** [alibaba/derrick#3]
执行  derrick -h

输出：
Failed to load rigging or commands in disk,because of No module named python_platform
Usage:

**Comment by ringtail** [comment]
能提供些更具体的信息吗，比如操作系统、Python的版本、装的方式。

**Comment by ringtail** [comment]
已经修复了，可以再试下

**Comment by jearton** [comment]
mac python2.7.13 通过pip装的

**Comment by ringtail** [comment]
已经修复了，可以试下吗
