### ISSUE TITLE
兼容问题

### ISSUE THREAD

**Issue by guyeu** [alibaba/derrick#38]
该工具只有在`prompt-toolkit==1.0.15`环境才能使用，这和`jupyter-console``ipython`是冲突的。
强烈建议保持对最新版本工具链的兼容，或者构建二进制包。

**Comment by ringtail** [comment]
@Oldmoooon 是windows吗？

**Comment by Oldmoooon** [comment]
> @Oldmoooon 是windows吗？

是mac。

**Comment by ringtail** [comment]
> > @Oldmoooon 是windows吗？
> 是mac。
可以的，binary是可以的，下一个release，我打一下binary

**Comment by ringtail** [comment]
@guyeu Try the latest version pls.

**Comment by guyeu** [comment]
好了~
