### ISSUE TITLE
安装报错这个如何解决

### ISSUE THREAD

**Issue by liyin37** [alibaba/derrick#41]
Collecting certifi>=2017.4.17
  Using cached certifi-2019.11.28-py2.py3-none-any.whl (156 kB)
ERROR: requests 2.20.0 has requirement idna<2.8,>=2.5, but you'll have idna 2.8 which is incompatible.
ERROR: requests 2.20.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.8 which is incompatible.
Installing collected packages: regex, whaaaaat, pychalk, simplejson, setuptools-git, idna, nose, certifi, chardet, urllib3, requests, requests-toolbelt, pkginfo, tqdm, python-derrick
    Running setup.py install for regex ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ru3YeY/regex/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ru3YeY/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zdC9ru/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python2.7/regex
         cwd: /tmp/pip-install-ru3YeY/regex/
    Complete output (20 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/regex
    copying regex_2/__init__.py -> build/lib.linux-x86_64-2.7/regex
    copying regex_2/regex.py -> build/lib.linux-x86_64-2.7/regex
    copying regex_2/_regex_core.py -> build/lib.linux-x86_64-2.7/regex
    copying regex_2/test_regex.py -> build/lib.linux-x86_64-2.7/regex
    running build_ext
    building 'regex._regex' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/regex_2
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-5Z483E/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c regex_2/_regex.c -o build/temp.linux-x86_64-2.7/regex_2/_regex.o
    regex_2/_regex.c:48:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ru3YeY/regex/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ru3YeY/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zdC9ru/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python2.7/regex Check the logs for full command output.

**Comment by ringtail** [comment]
麻烦提供下系统的版本

**Comment by liyin37** [comment]
> 麻烦提供下系统的版本
[root@docker ~]# cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)
[root@docker ~]# python -V
Python 3.7.3
[root@docker ~]#

**Comment by ringtail** [comment]
> > 麻烦提供下系统的版本
> > [root@docker ~]# cat /etc/redhat-release
> > CentOS Linux release 7.7.1908 (Core)
> > [root@docker ~]# python -V
> > Python 3.7.3
> > [root@docker ~]#

好的，我看下Python3.7的兼容性

**Comment by liyin37** [comment]
是更新代码了吗，我使用python 2.7.17 也无法安装
Using cached certifi-2019.11.28-py2.py3-none-any.whl (156 kB)
ERROR: requests 2.22.0 has requirement idna<2.9,>=2.5, but you'll have idna 2.9 which is incompatible.
Installing collected packages: regex, whaaaaat, pychalk, simplejson, setuptools-git, idna, nose, certifi, chardet, urllib3, requests, requests-toolbelt, pkginfo, tqdm, python-derrick
    Running setup.py install for regex ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-LpffN8/regex/setup.py'"'"'; __file__='"'"'/tmp/pip-install-LpffN8/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-afC3n9/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python2.7/regex
         cwd: /tmp/pip-install-LpffN8/regex/
    Complete output (20 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/regex
    copying regex_2/__init__.py -> build/lib.linux-x86_64-2.7/regex
    copying regex_2/regex.py -> build/lib.linux-x86_64-2.7/regex
    copying regex_2/_regex_core.py -> build/lib.linux-x86_64-2.7/regex
    copying regex_2/test_regex.py -> build/lib.linux-x86_64-2.7/regex
    running build_ext
    building 'regex._regex' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/regex_2
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-5Z483E/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c regex_2/_regex.c -o build/temp.linux-x86_64-2.7/regex_2/_regex.o
    regex_2/_regex.c:48:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-LpffN8/regex/setup.py'"'"'; __file__='"'"'/tmp/pip-install-LpffN8/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-afC3n9/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python2.7/regex Check the logs for full command output.

**Comment by ringtail** [comment]
centos需要安装下python-devel

**Comment by ringtail** [comment]
另外测试下3.7的版本，应该已经可以工作了

**Comment by ringtail** [comment]
if you find some error like: fatal error: Python.h: No such file or directory,Please install python-dev or python-devel with package manager.Windows please use powershell or winshell.

**Comment by liyin37** [comment]
![image](https://user-images.githubusercontent.com/42507175/75156608-6bbf0300-574d-11ea-8e94-c0ec0def0b71.png)
安装完成后执行Derrick 报错了

**Comment by liyin37** [comment]
Traceback (most recent call last):
  File "/usr/bin/derrick", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/python3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/local/python3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/python3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/python3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/python3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/python3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-derrick==0.1.0' distribution was not found and is required by the application

**Comment by ringtail** [comment]
Try to uninstall the old version and install with the command below `pip3 install python-derrick==0.1.1 --index-url=https://pypi.org/simple`

**Comment by ChongmingDu** [comment]
@ringtail Python 3.7.7 available
