### ISSUE TITLE
Failed to load rigging or commands in disk,because of cannot import name Token

### ISSUE THREAD

**Issue by hatzhang** [alibaba/derrick#45]
At the first run, i got the following error
`
Failed to load rigging or commands in disk,because of cannot import name Token
`
what to do about this?
Derrick is installed under sudo.

**Comment by ringtail** [comment]
try ` pip install prompt_toolkit `

**Comment by ringtail** [comment]
try `pip3 install --index-url=https://pypi.python.org/simple python-derrick==0.1.2 --no-cache-dir`
