### ISSUE TITLE
在go语言上运行失败

### ISSUE THREAD

**Issue by daxiondi** [alibaba/derrick#65]
- 本地go语言版本
![image](https://user-images.githubusercontent.com/26639571/110411237-2e61b500-80c5-11eb-9712-3f38bd47d45b.png)
- derrick 版本
```
0.1.2
```
运行命令
```
derrick init
```
运行出现问题
Failed to detect your application's platform.Maybe you can upgrade Derrick to get more platforms supported.

文档给的go语言示例程序也有这样的问题

**Comment by hongchaodeng** [comment]
@daxiondi 你好！`init` 命令已经不支持了。请改用 `gen`：https://github.com/alibaba/derrick#build-golang-application

而且 Go 版本需要是 1.16 。同时 git pull derrick 最新的 code。

有啥问题欢迎继续反馈！

**Comment by hongchaodeng** [comment]
@daxiondi 请问还有什么能帮到您的吗？

**Comment by daxiondi** [comment]
现在暂时没有时间弄这个，我会按照你说的重新在试下，有问题在重新打开issue
