### ISSUE TITLE
pip3 install 

### ISSUE THREAD

**Issue by skCNA** [alibaba/derrick#70]
mac 10.15.7

lishuang@newuser derrick % sudo pip3 install python-derrick
Requirement already satisfied: python-derrick in /Library/Python/3.7/site-packages (0.1.2)
Requirement already satisfied: whaaaaat==0.5.2 in /Library/Python/3.7/site-packages (from python-derrick) (0.5.2)
Requirement already satisfied: pychalk==1.1.0 in /Library/Python/3.7/site-packages (from python-derrick) (1.1.0)
Requirement already satisfied: docopt==0.6.2 in /Library/Python/3.7/site-packages (from python-derrick) (0.6.2)
Requirement already satisfied: simplejson==3.13.2 in /Library/Python/3.7/site-packages (from python-derrick) (3.13.2)
Requirement already satisfied: prompt-toolkit==1.0.15 in /Library/Python/3.7/site-packages (from python-derrick) (1.0.15)
Requirement already satisfied: Jinja2==2.10 in /Library/Python/3.7/site-packages (from python-derrick) (2.10)
Requirement already satisfied: chardet==3.0.4 in /Library/Python/3.7/site-packages (from python-derrick) (3.0.4)
Requirement already satisfied: MarkupSafe>=0.23 in /Library/Python/3.7/site-packages (from Jinja2==2.10->python-derrick) (1.1.1)
Requirement already satisfied: six>=1.9.0 in /Library/Python/3.7/site-packages (from prompt-toolkit==1.0.15->python-derrick) (1.15.0)
Requirement already satisfied: wcwidth in /Library/Python/3.7/site-packages (from prompt-toolkit==1.0.15->python-derrick) (0.2.5)
Requirement already satisfied: Pygments>=2.2.0 in /Library/Python/3.7/site-packages (from whaaaaat==0.5.2->python-derrick) (2.8.1)
Requirement already satisfied: regex>=2016.11.21 in /Library/Python/3.7/site-packages (from whaaaaat==0.5.2->python-derrick) (2021.3.17)

没有derrick命令

lishuang@newuser derrick % de
debinhex.pl      debinhex5.28.pl  decryptdir       delv             dev_mkdb
debinhex5.18.pl  declare          defaults         desdp

咋用的

**Comment by hongchaodeng** [comment]
您好，最新版 derrick 没有任何 pip 安装路径。
安装方式是通过 Go 来构建：https://github.com/alibaba/derrick#installation

**Comment by skCNA** [comment]
好的，谢谢

**Comment by skCNA** [comment]
lishuang@newuser derrick-0.1.2 % make build
go build -o _bin/derrick main.go
go: github.com/AlecAivazis/survey/v2@v2.2.7: Get "https://proxy.golang.org/github.com/%21alec%21aivazis/survey/v2/@v/v2.2.7.mod": dial tcp 216.58.200.241:443: i/o timeout
make: *** [build] Error 1

**Comment by skCNA** [comment]
lishuang@newuser derrick-0.1.2 % go version
go version go1.16.2 darwin/amd64

**Comment by skCNA** [comment]
lishuang@newuser derrick-0.1.2 % make build
go build -o _bin/derrick main.go
go: github.com/AlecAivazis/survey/v2@v2.2.7: Get "https://proxy.golang.org/github.com/%21alec%21aivazis/survey/v2/@v/v2.2.7.mod": net/http: TLS handshake timeout
make: *** [build] Error 1

**Comment by skCNA** [comment]
go env -w GOPROXY=https://goproxy.cn,direct

设置下代理，解决
